### ISSUE TITLE
How to display title with the indicator?

### ISSUE THREAD

**Issue by hcrgithub** [YahyaBagia/YBHud#1]
Thanks for making such a productive library, but I've a scenario where I need to display a title with the loader. 

Can you please point out the steps where modifications will be required?
Example : text at top, left, bottom or right of the loader?

Regards

**Comment by YahyaBagia** [comment]
@hcrgithub : Currently it is not supported. Hopefully I will add this feature soon.

**Comment by YahyaBagia** [comment]
@hcrgithub YBHud now supports text below ActivityIndicator. If it fulfills your purpose then close this issue.
